name: Version & Tag

on:
  push:
    branches:
      - main
      - develop

jobs:
  version:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org/"

      - name: Install Yarn
        run: npm install --global yarn

      - name: 📦 Install dependencies
        run: yarn

      - name: Enter pre mode for beta (only on develop)
        if: github.ref == 'refs/heads/develop'
        run: |
          if [ ! -f .changeset/pre.json ]; then
            npx changeset pre enter beta
          else
            echo "Already in pre mode, skipping"
          fi

      - name: Exit pre mode (only on main)
        if: github.ref == 'refs/heads/main'
        run: npx changeset pre exit

      - name: Create version bump commit or tag
        uses: changesets/action@v1
        with:
          publish: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
