name: Version & Tag

on:
  push:
    branches:
      - main
      - develop

jobs:
  version:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org/"

      - name: Install Yarn
        run: npm install --global yarn

      - name: 📦 Install dependencies
        run: yarn

      - name: 🔨 Build package
        run: yarn build

      - name: Run tests
        run: yarn test

      - name: Enter pre mode for beta (only on develop)
        if: github.ref == 'refs/heads/develop'
        run: |
          if [ ! -f .changeset/pre.json ]; then
            npx changeset pre enter beta
          fi

      - name: Exit pre mode (only on main)
        if: github.ref == 'refs/heads/main'
        run: |
          if [ -f .changeset/pre.json ]; then
            npx changeset pre exit
          fi

      - name: Version packages
        run: npx changeset version

      - name: Commit version bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: version bump [skip ci]" || echo "No changes to commit"

      - name: Push version bump
        run: git push origin HEAD:${{ github.ref_name }}

      - name: Tag and push
        run: |
          VERSION=$(node -p "require('./package.json').version")
          git tag v$VERSION
          git push origin v$VERSION

      - name: Publish to npm
        run: |
          if [[ "${GITHUB_REF}" == *"-beta."* ]]; then
            npm publish -- --tag beta
          else
            npm publish
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
